import Head from 'next/head'
import React, { useRef, useState, Suspense } from 'react'

export default function About() {

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>

                Senior front-end developer with more than 5 years of experience in web application development, experience in the MERN stack and in creating highly usable and attractive user interfaces. With skills in functional and reactive programming, I focus on developing scalable and efficient solutions using modern technologies and strongly typed languages. I have worked on diverse projects, from web applications to mobile applications, with experience in e-invoicing, banking and management systems. I am a developer committed to quality and customer satisfaction, always looking to overcome technical challenges and deliver high quality solutions.
                
            </main>
        </>
    )
}