import Head from 'next/head'
import React, { useRef, useState, Suspense } from 'react'
import styled from "styled-components";

const Box = styled.div`
  background: #3343538a;
  position: absolute;
  display: flex;
  top: 10;
  left: 0;
  width: 400px;
  height: 400px;
  margin: 64px;
  font-family: Roboto, Arial, sans-serif;
  font-weight: bold;
  text-align: center;
  color: #66ff00ef;
  text-shadow: 1px 1px 3px #77ee11;
  backdrop-filter: blur(6px) saturate(0.8) brightness(5);
  z-index: 2;
  overflow: visible;
  clip-path: polygon(
    0 50px,
    0 0,
    350px 0,
    400px 50px,
    400px 350px,
    400px 400px,
    50px 400px,
    0% 350px,
    0% 50px
  );
  & p {
    margin: 16px;
  }
`;
// const Path = styled(motion.path)`
//   fill: none;
//   stroke: #236343;
//   stroke-width: 4;
//   stroke-miterlimit: 10;
// `;
// const Svg = styled(motion.svg)`
//   outline: none;
//   top: 10;
//   left: 0;
//   width: 400px;
//   height: 400px;
//   margin: 64px;
//   z-index: 3;
//   position: absolute;
//   flex: 1;
//   overflow: visible;
//   transition-duration: 0.4s;
//   transition-timing-function: ease;
//   scale: 0.95;
//   &:hover {
//     transform: translateY(-20px);
//   }
// `;

export default function Home() {

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Box>hola</Box>
            </main>
        </>
    )
}