import Head from 'next/head'
import { Inter } from 'next/font/google'
import React, { useState, Suspense } from 'react'
import { Canvas, useLoader } from '@react-three/fiber'
import { MapControls } from '@react-three/drei'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import styled from "styled-components";
import { motion } from "framer-motion";
import Link from 'next/link'

const Box = styled.div`
  background: #00553e40;
  backdrop-filter: blur(8px) brightness(1.4);
  position: absolute;
  display: flex;
  top: 10;
  left: 0;
  width: 400px;
  height: 400px;
  margin: 64px;
  font-family: Arial, sans-serif;
  font-weight: bold;
  text-align: center;
  color: #66ff00ef;
  text-shadow: 1px 1px 3px #77ee11;
  padding: 16px;
  z-index: 2;
  overflow: visible;
  clip-path: polygon(
    0 50px,
    0 0,
    350px 0,
    400px 50px,
    400px 350px,
    400px 400px,
    50px 400px,
    0% 350px,
    0% 50px
  );
  & p {
    margin: 16px;
  }
`;
const Content = styled.div`
  position: fixed;
  top: 0;
  left: 0;
  width: 400px;
  height: 400px;
  margin: 64px;
  z-index: 3;
  display: flex;
`
const Path = styled(motion.path)`
  fill: none;
  stroke: #236343;
  stroke-width: 4;
  stroke-miterlimit: 10;
`;
const Svg = styled(motion.svg)`
  outline: none;
  top: 10;
  left: 0;
  width: 400px;
  height: 400px;
  margin: 64px;
  z-index: 3;
  position: absolute;
  flex: 1;
  overflow: visible;
  transition-duration: 0.4s;
  transition-timing-function: ease;
  scale: 0.95;
  &:hover {
    transform: translateY(-20px);
  }
`;

const MenuConetent = styled.div`

  background: #00553e40;
  backdrop-filter: blur(8px);
  position: fixed;
  top: 0;
  left: 50%;
  z-index: 4; 
padding: 16px;
`
const Linked = styled(Link)`
 margin: 16px;
`
const line1 = "M0 0L350 0L400 50L400 400L50 400L0 350Z";

const inter = Inter({ subsets: ['latin'] })

function Model() {

  const gltf = useLoader(GLTFLoader, './base_map.glb');

  const rotation = [0, Math.PI / 4, 0]; // Rotar 90 grados en el eje Y
  const position = [0, 0, 0]; // Posicionar en el centro de la escena

  return <primitive object={gltf.scene} scale={4} rotation={rotation} position={position} />;
}
function Menu() {
  return (
    <MenuConetent>
      <Linked href="/home">Home</Linked>
      <Linked href="/">lol</Linked>
      <Linked href="/contact">Contact</Linked>
    </MenuConetent>
  )
}

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Menu />
        <Canvas orthographic camera={{ position: [0, 250, 0], zoom: 10 }}>
          <color attach="background" args={['#252530']} />
          <ambientLight />
          <hemisphereLight intensity={0.125} color="#8040df" groundColor="red" />
          <spotLight castShadow color="orange" intensity={2} position={[-50, 50, 40]} angle={0.25} penumbra={1} shadow-mapSize={[128, 128]} shadow-bias={0.00005} />
          <gridHelper args={[1000, 100, '#151515', '#020202']} position={[0, 1, 0]} />
          <pointLight position={[10, 100, 10]} />
          <Suspense fallback={null}>
            <Model />
          </Suspense>
          <MapControls
            minZoom={10}
            maxZoom={15}
            enableDamping
            dampingFactor={0.05}
            minPolarAngle={Math.PI / 4}
            maxPolarAngle={Math.PI / 3}
            minAzimuthAngle={Math.PI / 5}
            maxAzimuthAngle={Math.PI / 3}
            addEventListener={undefined}
            hasEventListener={undefined}
            removeEventListener={undefined}
            dispatchEvent={undefined}
            onEnd={e => {
              if (e === undefined) return;
              e.target.target.x > 300 ? e.target.target.x = 300 : null;
              e.target.target.x < -300 ? e.target.target.x = -300 : null;
              e.target.target.z > 300 ? e.target.target.z = 300 : null;
              e.target.target.z < -300 ? e.target.target.z = -300 : null;
              e.target.target.y > 300 ? e.target.target.y = 300 : null;
              e.target.target.y < -300 ? e.target.target.y = -300 : null;
            }}
          />
        </Canvas>
        <Content>
          <Suspense fallback={null}>
            <Box>Welcome</Box>
            <Svg
              version="1.1"
              id="Capa_1"
              xmlns="http://www.w3.org/2000/svg"
              x="0px"
              y="0px"
              viewBox="0 0 400 400"
              whileHover={{ scale: 1.1 }}
              whileTap={{ scale: 1 }}
            >
              <Path d={line1} />
            </Svg>
          </Suspense>
        </Content>

      </main>
    </>
  )
}