import Head from 'next/head'
import React, { useRef, useState, Suspense } from 'react'
import {Box, ContentBox } from "../styles/Styles"
export default function Projects() {

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <ContentBox>

                <Box>
                    Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates praesentium pariatur quidem quaerat asperiores, officiis adipisci perferendis. Neque incidunt, aliquam recusandae quasi, ut porro amet similique, dolorum quis modi voluptatibus!
                </Box>
                <Box>
                    Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates praesentium pariatur quidem quaerat asperiores, officiis adipisci perferendis. Neque incidunt, aliquam recusandae quasi, ut porro amet similique, dolorum quis modi voluptatibus!
                </Box>
                <Box>
                    Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates praesentium pariatur quidem quaerat asperiores, officiis adipisci perferendis. Neque incidunt, aliquam recusandae quasi, ut porro amet similique, dolorum quis modi voluptatibus!
                </Box>
                <Box>
                    Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates praesentium pariatur quidem quaerat asperiores, officiis adipisci perferendis. Neque incidunt, aliquam recusandae quasi, ut porro amet similique, dolorum quis modi voluptatibus!
                </Box>
                <Box>
                    Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates praesentium pariatur quidem quaerat asperiores, officiis adipisci perferendis. Neque incidunt, aliquam recusandae quasi, ut porro amet similique, dolorum quis modi voluptatibus!
                </Box>
                <Box>
                    Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates praesentium pariatur quidem quaerat asperiores, officiis adipisci perferendis. Neque incidunt, aliquam recusandae quasi, ut porro amet similique, dolorum quis modi voluptatibus!
                </Box>
                </ContentBox>
            </main>
        </>
    )
}